import { useState } from "react";
import { motion } from "framer-motion";
import PageWrapper from "@/components/PageWrapper";
import { getCoupleId, setCoupleId } from "@/lib/tcb";

interface Props {
  onDone: () => void;
}

export default function CoupleSetup({ onDone }: Props) {
  const [mode, setMode] = useState<"choose" | "new" | "join">("choose");
  const [code, setCode] = useState("");
  const myCode = getCoupleId();

  const handleCreate = () => {
    // coupleId is already generated by getCoupleId()
    onDone();
  };

  const handleJoin = () => {
    if (code.trim().length < 4) return;
    setCoupleId(code.trim().toUpperCase());
    onDone();
  };

  return (
    <PageWrapper className="flex flex-col items-center justify-center text-center min-h-screen">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full max-w-xs"
      >
        <span className="text-5xl block mb-4">💕</span>
        <h1 className="text-xl font-bold mb-2">情侣共创</h1>
        <p className="text-sm text-muted-foreground mb-6">
          两个人使用同一个邀请码，数据实时共享
        </p>

        {mode === "choose" && (
          <div className="space-y-3">
            <button
              onClick={() => setMode("new")}
              className="w-full bg-primary text-primary-foreground py-3 rounded-2xl font-semibold"
            >
              ✨ 创建新空间
            </button>
            <button
              onClick={() => setMode("join")}
              className="w-full bg-secondary text-secondary-foreground py-3 rounded-2xl font-medium"
            >
              🔗 加入 TA 的空间
            </button>
          </div>
        )}

        {mode === "new" && (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">你的邀请码：</p>
            <div className="bg-card rounded-2xl p-4 text-2xl font-mono font-bold tracking-widest text-primary">
              {myCode}
            </div>
            <p className="text-xs text-muted-foreground">
              把这个码分享给 TA，TA 输入后就能一起用了
            </p>
            <button
              onClick={handleCreate}
              className="w-full bg-primary text-primary-foreground py-3 rounded-2xl font-semibold"
            >
              开始使用 ❤️
            </button>
            <button onClick={() => setMode("choose")} className="text-sm text-muted-foreground">
              ← 返回
            </button>
          </div>
        )}

        {mode === "join" && (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">输入 TA 的邀请码：</p>
            <input
              value={code}
              onChange={(e) => setCode(e.target.value.toUpperCase())}
              placeholder="例如：ABC123"
              maxLength={6}
              className="w-full bg-card rounded-2xl p-4 text-center text-2xl font-mono font-bold tracking-widest focus:outline-none focus:ring-2 focus:ring-primary/30"
            />
            <button
              disabled={code.trim().length < 4}
              onClick={handleJoin}
              className="w-full bg-primary text-primary-foreground py-3 rounded-2xl font-semibold disabled:opacity-40"
            >
              加入空间 💕
            </button>
            <button onClick={() => setMode("choose")} className="text-sm text-muted-foreground">
              ← 返回
            </button>
          </div>
        )}
      </motion.div>
    </PageWrapper>
  );
}
